export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
